### ISSUE TITLE
FCFS

### ISSUE THREAD

**Issue by dethorpe** [Theta1/CS149#10]

**Comment by dethorpe** [comment]
Looks really good! But always random? Need to setup fixed width results. For comparison. See my branch in a few

**Comment by siebenluke** [comment]
Like random numbers for the names? it's the seed number we pass in.

Anyways, I took a look at your branch and I would've gone with editing the printStringList() method to have a printf("%3s", process.getName()); or something along those lines to get 3 spaces per number/empty string.

**Comment by chaoservices** [comment]
Maybe the clone method?

**Comment by dethorpe** [comment]
Yeah. The names are a new random every time. I suspect the clone process.
That is probably smarter with the printf()

**Comment by dethorpe** [comment]
Nope, cloning seems to work via direct testing.

**Comment by dethorpe** [comment]
So I traced it down. We weren't using a seed.
But new problem: When we do the values returned are very non random!

**Comment by denniseh7** [comment]
Is the problem with the numbers because we use the same seed every run? If
it is, you can just set the seed to the current time so the seed keeps
changing.  Sorry, I've been busy so I haven't had time to finish SJF yet.
I'll try to get it done tomorrow afternoon at the CS club.

Dennis
